name: Create Release PR
on:
  push:
    branches:
      - 'releases/**'
jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          # TODO-3460: Change back to "main" branch
          destination_branch: 'DOP-3460-pr-workflow'
          pr_title: ${{ github.event.head_commit.message }}
          pr_body: |
            This is an automated PR.

            Please double-check that:

            - The correct component's version was updated.
            - The version was updated as intended.
            - The PR title is in the format "[RELEASE] - "
            - The PR is squashed with the same commit message.
            - The PR has an empty description.

            For more information, please see the [release](https://github.com/mongodb-forks/redoc/blob/main/.github/workflows/release.yml) workflow.
          pr_label: 'release'
